name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - uses: Gr1N/setup-poetry@v8

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        
    - run: poetry --version
  
    - name: Install dependencies with Poetry
      run: |
        poetry install 

    - name: Check code formatting with isort
      run: poetry run isort . --check-only

    - name: Check code formatting with black
      run: poetry run black . --check

    - name: Type-check with mypy
      run: poetry run mypy src 

    - name: Run pytest
      run: poetry run pytest
